use std::collections::HashMap;
use std::path::Path;
use std::sync::Mutex;

use image::RgbaImage;

/// Build-time asset generation (blending logos into folder artwork). Not
/// compiled into the shipping binary; see generator.rs for how to run it.
#[cfg(test)]
mod generator;

/// Dropbox-style folder icons: the root ~/Vercel folder gets the app's
/// triangle icon, and each project folder gets a dark rounded tile with its
/// framework's logo (Vercel's icon set, bundled from public/icons) badged
/// with deployment status (green ready / amber deploying / red failed).
///
/// Implemented with NSWorkspace on macOS. On Windows (desktop.ini) and Linux
/// (gio metadata) this is a planned native integration — the entry points
/// here are platform-neutral no-ops so nothing else needs cfg-gating.

/// The app's identity icon (dock in dev builds; bundled builds use
/// icon.icns generated from the same source).
const APP_ICON: &[u8] = include_bytes!("../../public/icon.png");

/// Finder artwork for the root ~/Vercel folder: the macOS folder with the
/// Vercel triangle (generated by the generate_folder_icons test).
const ROOT_FOLDER_ICON: &[u8] = include_bytes!("../../public/icons/mac/folder-vercel.png");

/// Pre-composited macOS folder + framework badge (public/icons/mac/).
fn framework_folder_png(framework: &str) -> &'static [u8] {
    match framework {
        "nextjs" => include_bytes!("../../public/icons/mac/folder-nextjs.png"),
        "nuxt" => include_bytes!("../../public/icons/mac/folder-nuxt.png"),
        "astro" => include_bytes!("../../public/icons/mac/folder-astro.png"),
        "remix" => include_bytes!("../../public/icons/mac/folder-remix.png"),
        "svelte" => include_bytes!("../../public/icons/mac/folder-svelte.png"),
        "vue" => include_bytes!("../../public/icons/mac/folder-vue.png"),
        "vite" => include_bytes!("../../public/icons/mac/folder-vite.png"),
        "react" => include_bytes!("../../public/icons/mac/folder-react.png"),
        "hono" => include_bytes!("../../public/icons/mac/folder-hono.png"),
        "express" => include_bytes!("../../public/icons/mac/folder-express.png"),
        _ => include_bytes!("../../public/icons/mac/folder-other.png"),
    }
}

/// Remember what we last painted per path so unchanged statuses don't
/// re-touch the filesystem (NSWorkspace calls are not free).
#[derive(Default)]
pub struct FolderIconCache(pub Mutex<HashMap<String, String>>);

fn status_color(status: &str) -> Option<[u8; 4]> {
    match status {
        "ready" => Some([69, 212, 131, 255]),
        "deploying" => Some([245, 166, 35, 255]),
        "failed" => Some([255, 77, 79, 255]),
        _ => None,
    }
}

fn blend(px: &mut image::Rgba<u8>, r: u8, g: u8, b: u8, alpha: f32) {
    let a = alpha.clamp(0.0, 1.0);
    px.0 = [
        (r as f32 * a + px.0[0] as f32 * (1.0 - a)) as u8,
        (g as f32 * a + px.0[1] as f32 * (1.0 - a)) as u8,
        (b as f32 * a + px.0[2] as f32 * (1.0 - a)) as u8,
        px.0[3].max((a * 255.0) as u8),
    ];
}

fn draw_status_dot(img: &mut RgbaImage, color: [u8; 4]) {
    let [r, g, b, _] = color;
    let w = img.width();
    let (cx, cy) = (w as f32 * 0.80, w as f32 * 0.80);
    let radius = w as f32 * 0.13;
    let ring = w as f32 * 0.027;
    for y in 0..img.height().min(w) {
        for x in 0..w {
            let d = ((x as f32 + 0.5 - cx).powi(2) + (y as f32 + 0.5 - cy).powi(2)).sqrt();
            if d <= radius + 1.0 {
                let px = img.get_pixel_mut(x, y);
                if d <= radius - ring {
                    blend(px, r, g, b, radius - ring - d + 0.5);
                    blend(px, r, g, b, 1.0);
                } else {
                    // White ring separates the dot from the artwork below.
                    blend(px, 255, 255, 255, (radius - d + 0.5).clamp(0.0, 1.0));
                }
            }
        }
    }
    // Refill the dot core over the ring gradient.
    let h = img.height().min(w);
    for y in 0..h {
        for x in 0..w {
            let d = ((x as f32 + 0.5 - cx).powi(2) + (y as f32 + 0.5 - cy).powi(2)).sqrt();
            if d <= radius - ring + 1.0 {
                let px = img.get_pixel_mut(x, y);
                blend(px, r, g, b, (radius - ring - d + 0.5).clamp(0.0, 1.0));
            }
        }
    }
}

/// Project folder icon: the pre-composited macOS folder + framework badge,
/// with the live status dot drawn on top.
fn project_icon_png(framework: &str, status: &str) -> Option<Vec<u8>> {
    let mut img = image::load_from_memory(framework_folder_png(framework))
        .ok()?
        .to_rgba8();
    if let Some(color) = status_color(status) {
        draw_status_dot(&mut img, color);
    }
    let mut out = std::io::Cursor::new(Vec::new());
    img.write_to(&mut out, image::ImageFormat::Png).ok()?;
    Some(out.into_inner())
}

fn root_icon_png() -> Option<Vec<u8>> {
    // Already a PNG — hand it to NSWorkspace as-is.
    Some(ROOT_FOLDER_ICON.to_vec())
}

#[cfg(target_os = "macos")]
fn set_folder_icon(path: &Path, png: &[u8]) -> bool {
    use objc2::AllocAnyThread;
    use objc2_app_kit::{NSImage, NSWorkspace, NSWorkspaceIconCreationOptions};
    use objc2_foundation::{NSData, NSString};

    let data = NSData::with_bytes(png);
    let Some(img) = NSImage::initWithData(NSImage::alloc(), &data) else {
        return false;
    };
    let ws = NSWorkspace::sharedWorkspace();
    let ns_path = NSString::from_str(&path.to_string_lossy());
    ws.setIcon_forFile_options(Some(&img), &ns_path, NSWorkspaceIconCreationOptions::empty())
}

#[cfg(not(target_os = "macos"))]
fn set_folder_icon(_path: &Path, _png: &[u8]) -> bool {
    false
}

/// Set the Dock icon at runtime. Bundled builds get it from icon.icns, but
/// `tauri dev` runs an unbundled binary that would otherwise show the
/// generic icon.
#[cfg(target_os = "macos")]
pub fn set_dock_icon() {
    use objc2::AllocAnyThread;
    use objc2_app_kit::{NSApplication, NSImage};
    use objc2_foundation::{MainThreadMarker, NSData};

    let Some(mtm) = MainThreadMarker::new() else { return };
    let data = NSData::with_bytes(APP_ICON);
    if let Some(img) = NSImage::initWithData(NSImage::alloc(), &data) {
        let app = NSApplication::sharedApplication(mtm);
        unsafe { app.setApplicationIconImage(Some(&img)) };
    }
}

#[cfg(not(target_os = "macos"))]
pub fn set_dock_icon() {}

fn apply_icon(cache: &FolderIconCache, path: &Path, cache_key: &str, png: Option<Vec<u8>>) {
    let path_key = path.to_string_lossy().to_string();
    {
        let mut seen = cache.0.lock().unwrap();
        if seen.get(&path_key).map(String::as_str) == Some(cache_key) {
            return;
        }
        seen.insert(path_key, cache_key.to_string());
    }
    if let Some(png) = png {
        let _ = set_folder_icon(path, &png);
    }
}

/// Give the root folder the plain app icon. Called once at setup.
pub fn apply_root_icon(cache: &FolderIconCache, root: &Path) {
    if root.is_dir() {
        apply_icon(cache, root, "root", root_icon_png());
    }
}

/// Badge each project folder: framework logo + current status.
/// Tuples are (name, status, framework).
pub fn apply_project_icons(
    cache: &FolderIconCache,
    root: &Path,
    projects: &[(String, String, String)],
) {
    for (name, status, framework) in projects {
        let dir = root.join(name);
        if dir.is_dir() {
            let key = format!("{framework}:{status}");
            apply_icon(cache, &dir, &key, project_icon_png(framework, status));
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn project_icons_encode_for_every_framework_and_status() {
        for framework in [
            "nextjs", "nuxt", "astro", "remix", "svelte", "vue", "vite", "react", "hono",
            "express", "static", "unknown",
        ] {
            for status in ["ready", "deploying", "failed", "idle"] {
                let png = project_icon_png(framework, status)
                    .unwrap_or_else(|| panic!("{framework}/{status} renders"));
                assert_eq!(&png[..8], &[0x89, b'P', b'N', b'G', b'\r', b'\n', 0x1a, b'\n']);
            }
        }
    }

    #[test]
    fn root_icon_encodes() {
        assert!(root_icon_png().is_some());
    }

    #[test]
    fn cache_prevents_redundant_paints() {
        let cache = FolderIconCache::default();
        let path = Path::new("/nonexistent/x");
        apply_icon(&cache, path, "nextjs:ready", None);
        apply_icon(&cache, path, "nextjs:ready", None);
        assert_eq!(cache.0.lock().unwrap().len(), 1);
    }

    #[test]
    #[ignore] // manual inspection helper: cargo test -p vercel-folder -- --ignored
    fn dump_folder_icons() {
        for (framework, status) in [
            ("nextjs", "ready"),
            ("astro", "deploying"),
            ("unknown", "failed"),
            ("react", "idle"),
        ] {
            let png = project_icon_png(framework, status).unwrap();
            let path = std::env::temp_dir().join(format!("folder-{framework}-{status}.png"));
            std::fs::write(&path, png).unwrap();
            println!("wrote {}", path.display());
        }
    }
}
